language: ruby

services:
  - docker

before_install:
- docker pull jekyll/jekyll:3.8
- docker run --rm -it --volume="$PWD:/srv/jekyll" jekyll/jekyll:3.8 jekyll build

# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages     # test the gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-"
