# Dependencies
markdown:             redcarpet
highlighter:          pygments

# Site settings
title:                martinpeck.com
tagline:              'A Jekyll theme'
description:          'A blog, written by someone called Martin Peck'
baseurl:              "/"
url:                  "http://martinpeck.com"

author:
  name:               'Martin Peck'
  url:                https://twitter.com/martinpeck

github:
  repo:               https://github.com/martinpeck/martinpeck.com

paginate:             5

# Other settings
exclude:              - README.md
                      - Gemfile
                      - Gemfile.lock
                      - Rakefile
                      - vendor
                      - .travis.yml

permalink:            none
