# Site settings
title: martinpeck.com

description: > # this means to ignore newlines until "baseurl:"
  A blog, written by someone called Martin Peck.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://martinpeck.com" # the base hostname & protocol for your site
twitter_username: martinpeck
github_username:  martinpeck
linkedin_username: martinpeck

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: :categories/:title
