# Site
name: martinpeck.com
title: martinpeck.com
copyright_name: Martin Peck
description: "A blog, written by someone called Martin Peck"
meta_description: "A blog, written by someone called Martin Peck."
logo: 'assets/icons/apple-icon.png'
google_analytics: 'UA-67509161-1'
disqus: martinpeck-com
permalink: pretty

# Authors
authors:
  mpeck:
    name: Martin
    display_name: Martin Peck
    gravatar: e7abf15c907e020b93f8be6f5f2ae672
    email: martinjohnpeck@gmail.com
    web: https://martinpeck.com
    twitter: https://twitter.com/martinpeck
    description: "I write code, and manage people who write code."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-gist

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 9
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge

# Ignore stuff
exclude:
  - README.md
  - LICENSE.md
  - vendor