name: Build Jekyll Site

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the container
      run: |
        docker run -v $(pwd):/workspace \
        mcr.microsoft.com/vscode/devcontainers/ruby:2.7-bullseye \
        /bin/bash -c "cd workspace && make ci-build"
